---
title: "Pre course survey summary"
author: Taavi Päll
output: 
  github_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load required functions (libraries):
```{r}
library(tidyverse)
library(googlesheets)
```

## Import data

Download query spreadsheet from google drive:
```{r}
(my_sheets <- gs_ls())
```

Identify query sheet:
```{r}
(surv <- gs_title("Pre-course survey (Responses)"))
```

Import data to table (data_frame):
```{r}
(responses <- surv %>% gs_read())
```

Convert wide table to long format (gather):
```{r}
(resp_gathered <- responses %>% 
  gather(key = key, value = value, -Timestamp))
```

## Results

**How big is your previous R experience?**
```{r}
resp_gathered %>% 
  filter(key == "How big is your previous R experience?") %>% 
  ggplot() +
  stat_count(mapping = aes(x = value)) +
  scale_x_discrete(labels = c("Null", "Little", "Have done\nsomething\nuseful")) +
  scale_y_continuous(breaks = seq(from = 0, to = 10, by = 2)) +
  labs(x = "How big is your previous R experience?")
```

